version: "3"
services:
  web:
    build: apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./apache/prestashop.conf:/etc/apache2/sites-enabled/prestashop.conf
      - ./prestashop:/app/prestashop

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123.
      MYSQL_DATABASE: dbname
      MYSQL_USER: user
      MYSQL_PASSWORD: abc123.
    volumes:
      - bbdd:/var/lib/mysql

volumes:
  bbdd:
