<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXexxid2\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXexxid2/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXexxid2.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXexxid2\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXexxid2\appProdProjectContainer([
    'container.build_hash' => 'Xexxid2',
    'container.build_id' => '0d4b83c3',
    'container.build_time' => 1677775044,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXexxid2');
